<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>../../src/jmespath.net.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JmesPath.Net.SourceOnly" Version="42.43.44" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\jmespathnet.tests\**\*.cs;" Exclude="..\jmespathnet.tests\**\AssemblyInfo.cs;..\jmespathnet.tests\bin\**\*.cs;..\jmespathnet.tests\obj\**\*.cs;" />
  </ItemGroup>

</Project>