<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>JmesPath.Net is a fully compliant JMESPATH parser.</Description>
    <AssemblyTitle>JmesPath.Net</AssemblyTitle>
    <VersionPrefix>1.0.330</VersionPrefix>
    <VersionSuffix>20260213.1</VersionSuffix>
    <Authors>Jeremie Devillard;Maxime Labelle;Stef Heyenrath</Authors>
    <TargetFrameworks>netstandard2.1;netstandard2.0</TargetFrameworks>
    <AssemblyName>JmesPath.Net</AssemblyName>
    <AssemblyOriginatorKeyFile>../jmespath.net.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
    <PackageId>Stef.JmesPath.Net</PackageId>
    <PackageTags>jmespath;json</PackageTags>
    <PackageProjectUrl>https://github.com/jdevillard/JmesPath.Net</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
	<PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
	<PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jmespath.net.parser\jmespath.net.parser.csproj" />
  </ItemGroup>

</Project>